/* Generated by the Systemtap dtrace wrapper */


#define _SDT_HAS_SEMAPHORES 1


#define STAP_HAS_SEMAPHORES 1 /* deprecated */


#include <sys/sdt.h>

/* SECEX_REQUEST_STARTUP ( char * request_file, char * request_uri, char * request_method ) */
#if defined STAP_SDT_V1
#define SECEX_REQUEST_STARTUP_ENABLED() __builtin_expect (request__startup_semaphore, 0)
#define secex_request__startup_semaphore request__startup_semaphore
#else
#define SECEX_REQUEST_STARTUP_ENABLED() __builtin_expect (secex_request__startup_semaphore, 0)
#endif
__extension__ extern unsigned short secex_request__startup_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define SECEX_REQUEST_STARTUP(arg1, arg2, arg3) \
DTRACE_PROBE3 (secex, request__startup, arg1, arg2, arg3)

/* SECEX_REQUEST_SHUTDOWN ( ) */
#if defined STAP_SDT_V1
#define SECEX_REQUEST_SHUTDOWN_ENABLED() __builtin_expect (request__shutdown_semaphore, 0)
#define secex_request__shutdown_semaphore request__shutdown_semaphore
#else
#define SECEX_REQUEST_SHUTDOWN_ENABLED() __builtin_expect (secex_request__shutdown_semaphore, 0)
#endif
__extension__ extern unsigned short secex_request__shutdown_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define SECEX_REQUEST_SHUTDOWN() \
DTRACE_PROBE (secex, request__shutdown)

/* SECEX_FUNCTION_EXECUTE ( char * request_file, char * function_name, int lineno ) */
#if defined STAP_SDT_V1
#define SECEX_FUNCTION_EXECUTE_ENABLED() __builtin_expect (function_execute_semaphore, 0)
#define secex_function_execute_semaphore function_execute_semaphore
#else
#define SECEX_FUNCTION_EXECUTE_ENABLED() __builtin_expect (secex_function_execute_semaphore, 0)
#endif
__extension__ extern unsigned short secex_function_execute_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define SECEX_FUNCTION_EXECUTE(arg1, arg2, arg3) \
DTRACE_PROBE3 (secex, function_execute, arg1, arg2, arg3)

